# Generated by Django 5.2.7 on 2025-10-06 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('codISBN', models.CharField(max_length=13, primary_key=True, serialize=False)),
                ('titolo', models.CharField(max_length=200)),
                ('anno', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Regione',
            fields=[
                ('cod', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Ricetta',
            fields=[
                ('numero', models.IntegerField(primary_key=True, serialize=False)),
                ('titolo', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('antipasto', 'Antipasto'), ('primo', 'Primo'), ('secondo', 'Secondo'), ('contorno', 'Contorno'), ('dessert', 'Dessert')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Pagina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeroPagina', models.IntegerField()),
                ('libro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ricette.libro')),
            ],
            options={
                'unique_together': {('libro', 'numeroPagina')},
            },
        ),
        migrations.CreateModel(
            name='RicettaPubblicata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pagina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ricette.pagina')),
                ('ricetta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ricette.ricetta')),
            ],
        ),
        migrations.AddField(
            model_name='ricetta',
            name='pubblicata_in',
            field=models.ManyToManyField(through='ricette.RicettaPubblicata', to='ricette.pagina'),
        ),
        migrations.CreateModel(
            name='RicettaRegionale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regione', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ricette.regione')),
                ('ricetta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ricette.ricetta')),
            ],
        ),
        migrations.AddField(
            model_name='ricetta',
            name='regioni',
            field=models.ManyToManyField(through='ricette.RicettaRegionale', to='ricette.regione'),
        ),
        migrations.CreateModel(
            name='Ingrediente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('ingrediente', models.CharField(max_length=100)),
                ('quantità', models.CharField(max_length=50)),
                ('ricetta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredienti', to='ricette.ricetta')),
            ],
            options={
                'unique_together': {('ricetta', 'numero')},
            },
        ),
    ]
